export const Users = [
    {
      id:1,
      profilePicture: "images/person/1.jpeg",
      username: "Jayne Jayne",
    },
    {
      id:2,
      profilePicture: "images/person/2.jpeg",
      username: "Janell Janell",
    },
    {
      id:3,
      profilePicture: "images/person/3.jpeg",
      username: "Alex Alex",
    },
    {
      id:4,
      profilePicture: "images/person/4.jpeg",
      username: "Dora Dora",
    },
    {
      id:5,
      profilePicture: "images/person/5.jpeg",
      username: "Thomas Thomas",
    },
    {
      id:6,
      profilePicture: "images/person/6.jpeg",
      username: "Shirley Shirley",
    },
    {
      id:7,
      profilePicture: "images/person/7.jpeg",
      username: "Travis Travis",
    },
    {
      id:8,
      profilePicture: "images/person/8.jpeg",
      username: "Kristen Kristen",
    },
    {
      id:9,
      profilePicture: "images/person/9.jpeg",
      username: "Gary Gary",
    },
    {
      id:10,
      profilePicture: "images/person/10.jpeg",
      username: "Bob Bob",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Train station.",
      photo: "images/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "images/post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Water.",
      photo: "images/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "images/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "images/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "images/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Children.",
      photo: "images/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "images/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      photo: "images/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "images/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];